/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "reading-note-card": {
    name: "reading-note-card",
    description: "A compact card for presenting a reading note with source, summary, and tags.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/reading-note-card/reading-note-card.tsx",
      type: "registry:component",
      target: "components/reading-note-card.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/reading-note-card/reading-note-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "reading-note-card-demo": {
    name: "reading-note-card-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/reading-note-card-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/reading-note-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}