/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/lib/utils.ts",
      type: "registry:lib",
      target: "@lib/utils.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chain-of-thought": {
    name: "chain-of-thought",
    description: "Visualize AI reasoning steps with search results, images, and progress states.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/chain-of-thought/chain-of-thought.tsx",
      type: "registry:component",
      target: "components/chain-of-thought.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/chain-of-thought/chain-of-thought.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mermaid-diagram": {
    name: "mermaid-diagram",
    description: "Render Mermaid diagrams inside a themed shadcn surface.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/mermaid-diagram/mermaid-diagram.tsx",
      type: "registry:component",
      target: "components/mermaid-diagram.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/mermaid-diagram/mermaid-diagram.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "context": {
    name: "context",
    description: "Display AI context window usage, token breakdowns, and cost estimates.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/context/context.tsx",
      type: "registry:component",
      target: "components/context.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/context/context.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "test-results": {
    name: "test-results",
    description: "Display test suite summaries, progress, collapsible suites, and error details.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/test-results/test-results.tsx",
      type: "registry:component",
      target: "components/test-results.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/test-results/test-results.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "suggestion": {
    name: "suggestion",
    description: "Display clickable prompt suggestions in a responsive horizontal row.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/suggestion/suggestion.tsx",
      type: "registry:component",
      target: "components/suggestion.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/suggestion/suggestion.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmer": {
    name: "shimmer",
    description: "Animate text with a sweeping shimmer that respects reduced motion.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/shimmer/shimmer.tsx",
      type: "registry:component",
      target: "components/shimmer.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/shimmer/shimmer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chain-of-thought-demo": {
    name: "chain-of-thought-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/chain-of-thought-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/chain-of-thought-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "mermaid-diagram-demo": {
    name: "mermaid-diagram-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/mermaid-diagram-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/mermaid-diagram-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "context-demo": {
    name: "context-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/context-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/context-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "test-results-demo": {
    name: "test-results-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/test-results-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/test-results-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "suggestion-demo": {
    name: "suggestion-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/suggestion-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/suggestion-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmer-demo": {
    name: "shimmer-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmer-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/shimmer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}